# Generated by Django 3.1.2 on 2020-10-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('tags', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/images')),
                ('song_file', models.FileField(upload_to='media/files')),
                ('movie', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'Songs',
            },
        ),
    ]
