# Generated by Django 3.1.2 on 2022-04-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'verbose_name_plural': 'Songs'},
        ),
    ]
