# Generated by Django 3.1.2 on 2020-10-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0002_auto_20201019_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='movie',
            field=models.CharField(default='album', max_length=200),
        ),
        migrations.AlterField(
            model_name='songs',
            name='song_file',
            field=models.FileField(upload_to='files'),
        ),
    ]
