# Generated by Django 3.1.2 on 2020-10-27 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0010_auto_20201023_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 17, 1, 29, 527829)),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
